# -*- coding: utf-8 -*-
"""DiwaliSalesAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjkFy96l4dO-yR8LThYTqKaheiY0xjKF
"""

!git clone https://github.com/rishabhnmishra/Python_Diwali_Sales_Analysis.git

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Python_Diwali_Sales_Analysis/Diwali Sales Data.csv",encoding='unicode_escape')

df.shape    #rows and columns

df.head(10)

df.describe()

df.isnull().sum()        #finding the null values in a particular column

df.isnull().sum().sum()

df.info()

df.drop(["Status","unnamed1"], axis=1, inplace=True)    #axis means vertical row delete inplace saves value.

df.describe()

df.info()               #it was showing error because i ran the code twice after deleting the rows above

df.dropna(inplace=True)

df.info()  #rows delete

"""data type change

"""

df["Amount"]=df["Amount"].astype('int')

df["Amount"].dtypes



"""***Exploratory data analysis***"""

a=sns.countplot(x="Gender",data=df)
for container in a.containers:
    a.bar_label(container)

plt.show()

df.groupby(["Gender"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False)

x=df.groupby(["Gender"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False)
sns.barplot(x="Gender",y="Amount",data=x)

""">>>females are the majority buyers

age group
"""

a=sns.countplot(x="Age Group",data=df, hue="Gender")
for container in a.containers:
    a.bar_label(container)

x=df.groupby(["Age Group"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False)
sns.barplot(x="Age Group",y="Amount",data=x)



""" 26-35 is the age group where most of the shopping happens!"""



x=df.groupby(["State"],as_index=False)["Orders"].sum().sort_values(by="Orders",ascending=False).head(10)
sns.set(rc={"figure.figsize":(20,5)})
sns.barplot(x="State",y="Orders",data=x)

x=df.groupby(["State"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False).head(10)
sns.set(rc={"figure.figsize":(20,5)})
sns.barplot(x="State",y="Amount",data=x)

a=sns.countplot(x="Marital_Status",data=df,)
sns.set(rc={"figure.figsize":(5,2)})
for container in a.containers:
    a.bar_label(container)

x=df.groupby(["Marital_Status","Gender"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False).head(10)
sns.set(rc={"figure.figsize":(3,3)})
sns.barplot(x="Marital_Status",y="Amount",data=x, hue="Gender")

"""married women are the highest number of buyers.

Occupation
"""

a=sns.countplot(x="Occupation",data=df,)
sns.set(rc={"figure.figsize":(20,7)})
for container in a.containers:
    a.bar_label(container)

x=df.groupby(["Occupation"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False).head(10)
sns.set(rc={"figure.figsize":(20,7)})
sns.barplot(x="Occupation",y="Amount",data=x, )

"""moat of the buyers are working in it healtcare and aviation"""

a=sns.countplot(x="Product_Category",data=df)
sns.set(rc={"figure.figsize":(25,10)})
for container in a.containers:
    a.bar_label(container)

x=df.groupby(["Product_Category"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False).head(10)
sns.set(rc={"figure.figsize":(20,10)})
sns.barplot(x="Product_Category",y="Amount",data=x)

"""food electronics and clothing are the most purchased products."""

x=df.groupby(["Product_ID"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False).head(10)
sns.set(rc={"figure.figsize":(20,7)})
sns.barplot(x="Product_ID",y="Amount",data=x)

